# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegespace', '0002_auto_20170319_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
